Add log out button & validate token for Users
CraftAcademy/fake_news_client_user pull request #15
Opened 2021-05-20 10:57 UTC by LucasKnudsen

[**PT-Story:**  ](https://www.pivotaltracker.com/story/show/178214061)
### User Story 
``` 
As a logged in user
In order to have a more seamless authentication
I want the site to remember be, but also be in control of if I want to be remembered 
``` 
## Changes proposed in this pull request: 
* 
## What I have learned working on this feature: 
*

2021-05-20 14:35 UTC, DavDan1 approved these changes

2021-05-20 14:39 UTC, SevaDer14 requested changes
remove the debugger))

2021-05-20 14:39 UTC, SevaDer14 commented on src/components/layout/Navbar.jsx
> +
empty div?

2021-05-20 14:39 UTC, SevaDer14 commented on src/modules/Authentication.js
> +        debugger;
oops

2021-05-20 16:44 UTC, LucasKnudsen commented on src/components/layout/Navbar.jsx
> +
For semantic purposes 😏

2021-05-20 16:44 UTC, LucasKnudsen commented on src/modules/Authentication.js
> +        debugger;
💯

2021-05-20 17:09 UTC, offcast-dev approved these changes

2021-05-20 17:49 UTC, 1CIM approved these changes

2021-05-21 04:53 UTC, tochman approved these changes
Goog job

2021-05-21 04:53 UTC, merged